
export const createSampleItems = () => {
  const sampleItems = [
    {
      title: "Vintage Levi's Denim Jacket",
      description: "Classic 90s denim jacket in excellent condition. Perfect for layering and creating trendy outfits. Shows minimal wear with authentic vintage character.",
      category: "Jackets",
      size: "M",
      type: "swap" as const,
      brand: "Levi's",
      condition: "Excellent",
      minRating: 3,
      isWashed: true,
      tags: ["#Vintage", "#Denim", "#90s"],
      images: ["https://images.unsplash.com/photo-1544966503-7cc5ac882d5e?w=400"],
      userId: "user1",
      username: "Sarah Chen",
      userAvatar: "https://images.unsplash.com/photo-1494790108755-2616b332b6c8?w=100",
      location: "Mumbai, India",
      status: "approved" as const
    },
    {
      title: "Designer Silk Scarf - Hermès Style",
      description: "Luxurious silk scarf with beautiful paisley pattern. Perfect for special occasions or adding elegance to any outfit.",
      category: "Accessories",
      size: "Free Size",
      type: "rent" as const,
      brand: "Hermès",
      condition: "Like New",
      rentPrice: 75,
      minRating: 4,
      isWashed: true,
      tags: ["#Designer", "#Silk", "#Luxury"],
      images: ["https://images.unsplash.com/photo-1601925260368-ae2f83cf8b7f?w=400"],
      userId: "user2",
      username: "Priya Sharma",
      userAvatar: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=100",
      location: "Delhi, India",
      status: "approved" as const
    },
    {
      title: "Trendy Crop Top",
      description: "Perfect summer crop top in mint green. Super comfortable and stylish for casual outings.",
      category: "Tops",
      size: "S",
      type: "swap" as const,
      brand: "Zara",
      condition: "Good",
      minRating: 2,
      isWashed: true,
      tags: ["#Summer", "#Casual", "#Trendy"],
      images: ["https://images.unsplash.com/photo-1551639505-5cae78dc31d6?w=400"],
      userId: "user3",
      username: "Ananya Kapoor",
      userAvatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=100",
      location: "Bangalore, India",
      status: "approved" as const
    },
    {
      title: "Elegant Black Dress",
      description: "Sophisticated little black dress perfect for formal events or date nights. Flattering fit with subtle details.",
      category: "Dresses",
      size: "M",
      type: "rent" as const,
      brand: "H&M",
      condition: "Excellent",
      rentPrice: 120,
      minRating: 3,
      isWashed: true,
      tags: ["#Formal", "#Elegant", "#LBD"],
      images: ["https://images.unsplash.com/photo-1566479179817-c0b8a9f80ac4?w=400"],
      userId: "user4",
      username: "Kavya Patel",
      userAvatar: "https://images.unsplash.com/photo-1508214751196-bcfd4ca60f91?w=100",
      location: "Pune, India",
      status: "approved" as const
    },
    {
      title: "Boho Maxi Dress",
      description: "Flowy bohemian maxi dress with beautiful floral print. Perfect for festivals and summer events.",
      category: "Dresses",
      size: "L",
      type: "swap" as const,
      brand: "Forever 21",
      condition: "Good",
      minRating: 2,
      isWashed: true,
      tags: ["#Boho", "#Maxi", "#Floral"],
      images: ["https://images.unsplash.com/photo-1595777457583-95e059d581b8?w=400"],
      userId: "user5",
      username: "Riya Gupta",
      userAvatar: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=100",
      location: "Chennai, India",
      status: "approved" as const
    },
    {
      title: "Premium Points Exclusive Jumpsuit",
      description: "Exclusive designer jumpsuit available only through points redemption. Limited edition piece with unique design.",
      category: "Sets",
      size: "M",
      type: "redeem" as const,
      brand: "Designer Studio",
      condition: "Excellent",
      points: 500,
      minRating: 4,
      isWashed: true,
      tags: ["#Exclusive", "#Designer", "#Premium"],
      images: ["https://images.unsplash.com/photo-1594633312681-425c7b97ccd1?w=400"],
      userId: "user6",
      username: "Sneha Reddy",
      userAvatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100",
      location: "Hyderabad, India",
      status: "approved" as const
    },
    {
      title: "Classic White Sneakers",
      description: "Crisp white sneakers that go with everything. Comfortable for daily wear and versatile styling.",
      category: "Shoes",
      size: "7",
      type: "swap" as const,
      brand: "Adidas",
      condition: "Good",
      minRating: 2,
      isWashed: true,
      tags: ["#Sneakers", "#White", "#Casual"],
      images: ["https://images.unsplash.com/photo-1549298916-b41d501d3772?w=400"],
      userId: "user7",
      username: "Meera Singh",
      userAvatar: "https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?w=100",
      location: "Kolkata, India",
      status: "approved" as const
    },
    {
      title: "Leather Biker Jacket",
      description: "Edgy black leather jacket perfect for adding attitude to any outfit. Genuine leather with classic biker styling.",
      category: "Jackets",
      size: "L",
      type: "rent" as const,
      brand: "Zara",
      condition: "Excellent",
      rentPrice: 200,
      minRating: 3,
      isWashed: false,
      tags: ["#Leather", "#Edgy", "#Biker"],
      images: ["https://images.unsplash.com/photo-1551028719-00167b16eac5?w=400"],
      userId: "user8",
      username: "Arjun Mehta",
      userAvatar: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=100",
      location: "Gurgaon, India",
      status: "approved" as const
    },
    {
      title: "Designer Handbag",
      description: "Luxury handbag in perfect condition. Spacious interior with elegant design suitable for both day and evening wear.",
      category: "Accessories",
      size: "Free Size",
      type: "rent" as const,
      brand: "Michael Kors",
      condition: "Like New",
      rentPrice: 150,
      minRating: 4,
      isWashed: false,
      tags: ["#Luxury", "#Handbag", "#Designer"],
      images: ["https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=400"],
      userId: "user9",
      username: "Divya Jain",
      userAvatar: "https://images.unsplash.com/photo-1517841905240-472988babdf9?w=100",
      location: "Jaipur, India",
      status: "approved" as const
    },
    {
      title: "High-Waisted Jeans",
      description: "Trendy high-waisted jeans in classic blue wash. Comfortable fit with a flattering silhouette.",
      category: "Bottoms",
      size: "28",
      type: "swap" as const,
      brand: "American Eagle",
      condition: "Good",
      minRating: 2,
      isWashed: true,
      tags: ["#Jeans", "#HighWaisted", "#Classic"],
      images: ["https://images.unsplash.com/photo-1541099649105-f69ad21f3246?w=400"],
      userId: "user10",
      username: "Pooja Agarwal",
      userAvatar: "https://images.unsplash.com/photo-1494790108755-2616b332b6c8?w=100",
      location: "Ahmedabad, India",
      status: "approved" as const
    },
    {
      title: "Exclusive Designer Heels",
      description: "Premium designer heels available for points redemption. Perfect for special occasions and formal events.",
      category: "Shoes",
      size: "6",
      type: "redeem" as const,
      brand: "Jimmy Choo",
      condition: "Excellent",
      points: 750,
      minRating: 5,
      isWashed: false,
      tags: ["#Designer", "#Heels", "#Exclusive"],
      images: ["https://images.unsplash.com/photo-1543163521-1bf539c55dd2?w=400"],
      userId: "user11",
      username: "Ishita Sharma",
      userAvatar: "https://images.unsplash.com/photo-1520813792240-56fc4a3765a7?w=100",
      location: "Noida, India",
      status: "approved" as const
    },
    {
      title: "Cozy Oversized Sweater",
      description: "Perfect for chilly weather, this oversized sweater is both comfortable and stylish. Soft knit material.",
      category: "Tops",
      size: "L",
      type: "swap" as const,
      brand: "Gap",
      condition: "Good",
      minRating: 2,
      isWashed: true,
      tags: ["#Cozy", "#Oversized", "#Winter"],
      images: ["https://images.unsplash.com/photo-1434389677669-e08b4cac3105?w=400"],
      userId: "user12",
      username: "Nisha Kulkarni",
      userAvatar: "https://images.unsplash.com/photo-1492633423870-43d1cd2775eb?w=100",
      location: "Surat, India",
      status: "approved" as const
    },
    {
      title: "Statement Earrings",
      description: "Bold statement earrings that can transform any simple outfit. Perfect for parties and special occasions.",
      category: "Accessories",
      size: "Free Size",
      type: "rent" as const,
      brand: "Local Artisan",
      condition: "Excellent",
      rentPrice: 50,
      minRating: 3,
      isWashed: false,
      tags: ["#Statement", "#Earrings", "#Party"],
      images: ["https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?w=400"],
      userId: "user13",
      username: "Tanvi Shah",
      userAvatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=100",
      location: "Vadodara, India",
      status: "approved" as const
    },
    {
      title: "Formal Blazer",
      description: "Professional blazer perfect for office wear. Well-tailored with a modern fit that works for business meetings.",
      category: "Jackets",
      size: "M",
      type: "rent" as const,
      brand: "Arrow",
      condition: "Excellent",
      rentPrice: 100,
      minRating: 3,
      isWashed: true,
      tags: ["#Formal", "#Blazer", "#Professional"],
      images: ["https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400"],
      userId: "user14",
      username: "Rajesh Kumar",
      userAvatar: "https://images.unsplash.com/photo-1507591064344-4c6ce005b128?w=100",
      location: "Lucknow, India",
      status: "approved" as const
    },
    {
      title: "Vintage Band T-Shirt",
      description: "Authentic vintage band t-shirt from the 80s. Rare collector's item with original graphics and authentic wear.",
      category: "Tops",
      size: "M",
      type: "swap" as const,
      brand: "Vintage Original",
      condition: "Fair",
      minRating: 1,
      isWashed: true,
      tags: ["#Vintage", "#Band", "#Collectible"],
      images: ["https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=400"],
      userId: "user15",
      username: "Rohit Verma",
      userAvatar: "https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=100",
      location: "Indore, India",
      status: "approved" as const
    },
    {
      title: "Premium Yoga Set",
      description: "High-quality yoga set available for points redemption. Includes matching top and leggings in premium fabric.",
      category: "Sets",
      size: "S",
      type: "redeem" as const,
      brand: "Lululemon",
      condition: "Like New",
      points: 400,
      minRating: 4,
      isWashed: true,
      tags: ["#Yoga", "#Activewear", "#Premium"],
      images: ["https://images.unsplash.com/photo-1506629905963-b3b2d9f83c92?w=400"],
      userId: "user16",
      username: "Aditi Rao",
      userAvatar: "https://images.unsplash.com/photo-1529626455594-4ff0802cfb7e?w=100",
      location: "Kochi, India",
      status: "approved" as const
    },
    {
      title: "Summer Shorts",
      description: "Comfortable cotton shorts perfect for summer weather. Casual and versatile for everyday wear.",
      category: "Bottoms",
      size: "30",
      type: "swap" as const,
      brand: "Uniqlo",
      condition: "Good",
      minRating: 2,
      isWashed: true,
      tags: ["#Summer", "#Shorts", "#Casual"],
      images: ["https://images.unsplash.com/photo-1591195853828-11db59a44f6b?w=400"],
      userId: "user17",
      username: "Vikram Singh",
      userAvatar: "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=100",
      location: "Chandigarh, India",
      status: "approved" as const
    },
    {
      title: "Silk Evening Gown",
      description: "Elegant silk evening gown for special occasions. Beautiful draping and sophisticated design.",
      category: "Dresses",
      size: "M",
      type: "rent" as const,
      brand: "Designer Collection",
      condition: "Excellent",
      rentPrice: 300,
      minRating: 4,
      isWashed: true,
      tags: ["#Silk", "#Evening", "#Gown"],
      images: ["https://images.unsplash.com/photo-1566479179817-c0b8a9f80ac4?w=400"],
      userId: "user18",
      username: "Shreya Nair",
      userAvatar: "https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=100",
      location: "Thiruvananthapuram, India",
      status: "approved" as const
    },
    {
      title: "Casual Sneakers",
      description: "Comfortable everyday sneakers in great condition. Perfect for walking and casual activities.",
      category: "Shoes",
      size: "8",
      type: "swap" as const,
      brand: "Nike",
      condition: "Good",
      minRating: 2,
      isWashed: true,
      tags: ["#Sneakers", "#Casual", "#Comfortable"],
      images: ["https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=400"],
      userId: "user19",
      username: "Amit Joshi",
      userAvatar: "https://images.unsplash.com/photo-1547425260-76bcadfb4f2c?w=100",
      location: "Nagpur, India",
      status: "approved" as const
    },
    {
      title: "Designer Watch",
      description: "Luxury designer watch available for premium points redemption. Swiss movement with elegant design.",
      category: "Accessories",
      size: "Free Size",
      type: "redeem" as const,
      brand: "Tag Heuer",
      condition: "Excellent",
      points: 1000,
      minRating: 5,
      isWashed: false,
      tags: ["#Luxury", "#Watch", "#Designer"],
      images: ["https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=400"],
      userId: "user20",
      username: "Karan Malhotra",
      userAvatar: "https://images.unsplash.com/photo-1507591064344-4c6ce005b128?w=100",
      location: "Goa, India",
      status: "approved" as const
    }
  ];

  return sampleItems;
};
